// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Back: typeof import('./src/components/Back.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    Flicker: typeof import('./src/components/Flicker.vue')['default']
    CarbonHome: typeof import('virtual:vite-icons/carbon/home')['default']
    FeatherBriefcase: typeof import('virtual:vite-icons/feather/briefcase')['default']
    FeatherEdit3: typeof import('virtual:vite-icons/feather/edit3')['default']
    UilGithubAlt: typeof import('virtual:vite-icons/uil/github-alt')['default']
  }
}

export { }
