// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
  }
}

export { }
